### ISSUE TITLE
[EROR] 

### ISSUE THREAD

**Issue by wander8snail** [oldthreefeng/mts#2]
Get "https://a.jd.com//ajax/queryServerData.html": dial tcp 106.39.169.63:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by oldthreefeng** [comment]
网络正常情况是不会有问题的。
![image](https://user-images.githubusercontent.com/38313565/105682337-49b99c00-5f2d-11eb-8016-c63d8e64a7d5.png)
